### ISSUE TITLE
Breaking changes in Microsoft.NET.Sdk.Functions 1.0.19

### ISSUE THREAD

**Issue by mrcunninghamz** [holgerleichsenring/AutofacOnFunctions#5]
Reference: https://github.com/Azure/azure-webjobs-sdk/issues/1865

The OP also referenced a github that resolves the issue. not quite sure how to make it fit with Autofac... will be investigating, but thought I'd leave you with what I know.

https://github.com/DibranMulder/azure-functions-v2-dependency-injection

**Comment by mrcunninghamz** [comment]
I submitted a PR to the repo above with my Autofac integration. Feedback is very much welcomed!

**Comment by holgerleichsenring** [comment]
hi mrcunninghamz,

I am not too sure if you want to put the burden of handling the infrastructure in webjobs on the consumer of DI. Since version 1.0.21 it is the way to go to use the ExtensionStarup Class to start the process. Please have a look onto version 1.0.5 which goes in a similar direction (actually also to support .net framework, things had been separated in a certain way) but without putting to many details about the internals of the infrastructure on the consumer.

I am going to close this issue. When you want to discuss things, you can contact me via twitter, facebook or email or via codingsoul.de
