### ISSUE TITLE
Boostrapper Fails When Autofac is Upgraded

### ISSUE THREAD

**Issue by oh-yeah** [holgerleichsenring/AutofacOnFunctions#8]
**Problem:**
Upgrading Autofac to any version greater >= 4.7 causes an error in the bootstraper.

**Steps to Reproduce:**
- Install Autofac v4.7 or higher in the AutofacOnFunctions.Samples.NetStandard project. 
- Run it

**Error Message** 
Method 'CreateModules' in type 'AutofacOnFunctions.Samples.Bootstrap.Bootstrapper' from assembly 'AutofacOnFunctions.Samples.NetStandard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by holgerleichsenring** [comment]
thanks for adding, will have a look.

**Comment by holgerleichsenring** [comment]
Actually, I could reproduce this issue with azure functions sdk 1.0.21. This is a known issue in Azure Functions. [redirects in Azure Functions](https://github.com/Azure/azure-functions-host/issues/992). The article claims that with Azure Function GA it should be solved.

**Comment by holgerleichsenring** [comment]
- accidentically closed the issue

Unluckily it looks like it is not sufficient to just reference GA version (1.0.23). nuget package must reference webjobs 3.0.0 instead of rc1 for some reason. I'll update it an add a new nuget package soon.

**Comment by holgerleichsenring** [comment]
nuget package 1.0.14 had been uploaded, sources adopted, please give it a try.

**Comment by NinjaSciurus** [comment]
The issue is again (or still) present in the current version 1.0.14 (using Autofac 4.8.1, functions SDK 1.0.24 and webjobs 3.0.0) on netstandard2.0. Do you have any information regarding breaking changes (either in AutofacOnFunctions or its dependencies)? I have searched around on this error but I only find old and obsolete articles.

UPDATE: my fault, I had the Autofac 4.8.1 nuget explicitely installed. Removing this results in AutofacOnFunctions using its default version (4.0.0) and it works. Thanks for your work! :)

**Comment by holgerleichsenring** [comment]
oh, thanks, @NinjaSciurus. I was just scared that MS did some "fancy" stuff to azure functions that let the issue come up again. :-)
